"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
exports.PiiType = void 0;
var PiiType;
(function (PiiType) {
    PiiType["EMAIL"] = "EMAIL";
    PiiType["PHONE"] = "PHONE";
    PiiType["IP"] = "IP";
    PiiType["IPV6"] = "IPV6";
    PiiType["MAC"] = "MAC";
    PiiType["CARD"] = "CARD";
    PiiType["IBAN"] = "IBAN";
    PiiType["NAME"] = "NAME";
    PiiType["LOCATION"] = "LOCATION";
    PiiType["ORG"] = "ORG";
    PiiType["DATE"] = "DATE";
    PiiType["USERNAME"] = "USERNAME";
    PiiType["TIME"] = "TIME";
    PiiType["ID"] = "ID";
    PiiType["PASS"] = "PASS";
    PiiType["SOCIALNUMBER"] = "SOCIALNUMBER";
    PiiType["BLACKLIST"] = "BLACKLIST";
})(PiiType || (exports.PiiType = PiiType = {}));
